### ISSUE TITLE
Test cases fail on node 4.2.x

### ISSUE THREAD

**Issue by amb26** [aseemk/json5#102]
node 4.2.x is now the LTS version and so will be used in a widespread way. Our test cases fail on this node, because its V8 is sufficiently modern to include the upcoming ES6 rules for the two new wacky numeric literal types 0o and 0b - http://stackoverflow.com/questions/2803145/is-there-0b-or-something-similar-to-represent-a-binary-number-in-javascript

Constants of this kind are included in our test suite under the label "coffeescript" but unfortunately they are now valid for the purposes of "eval" which can no longer be depended on to only include ES5 features on node. As a result of this, we have 12 test failures where we expect the fixtures containing these kinds of constants to bomb out of "eval" with a SyntaxError but they now unfortunately parse.

I've listed the failures in this gist: https://gist.github.com/amb26/2a04a2b2b132b580adaa

Ideas I can think of for resolving this:

i) Give these 12 fixtures a different suffix (such as .txt6 or so) that indicate that, whilst WE expect to fail to parse them, "eval" should expect to parse them on a sufficiently recent node (we'd then do a version detect on process.version)
    i) a) Same as i) only rather than doing the version test, we just completely skip the eval step for these
ii) Simply ditch these fixtures completely (seems undesirable)
iii) Simply ditch our "eval" failure checks completely (seems undesirable)

Any other ideas?

**Comment by jordanbtucker** [comment]
I think I prefer solution ii. We could write a thousand test cases that are invalid JSON5. I think we should focus on passing test cases features and failing test cases for specific error messages.

**Comment by jordanbtucker** [comment]
Fixed by #103
