### ISSUE TITLE
Railroad diagrams for the JSON5 site?

### ISSUE THREAD

**Issue by RichMorin** [aseemk/json5#53]
I like the railroad diagrams on the JSON site (json.org).  I'd like to have these for the JSON5 site, as well.

**Comment by sykano** [comment]
I took the liberty of coding the diagrams for the mentioned diagram generator (by extending the diagrams from json.org with the extensions specified in the JSON5 readme).
Somebody should review them for correctness. I'm not quite sure about the string specification (e.g. Do one have to escape ' in a double-quoted string and vice versa?) and about the number specification (e.g. Is .0 legal?).

see pull request #104

**Comment by tomByrer** [comment]
Cool @sykano 
I forgot about this suggestion.  Ironically, I found just a few days ago https://github.com/tabatkins/railroad-diagrams

**Comment by jordanbtucker** [comment]
@sykano I mentioned this in the PR, but I'll say it again here. Thanks for the diagrams. I don't think the code repository is the best place for them though. If you'd like to update the [Wiki](https://github.com/aseemk/json5/wiki), that would be great. Thanks.
