### ISSUE TITLE
Better context for errors

### ISSUE THREAD

**Issue by ravi** [aseemk/json5#86]
It would help greatly if the command line `json5` invocation provides more context for errors. For instance the following error message does not help find and fix an error in a ~ 600 line config file:

````
/tmp/node_modules/json5/lib/json5.js:54
            throw error;
                  ^
SyntaxError: Expected ']' instead of '{'
````

**Comment by jordanbtucker** [comment]
Fixed by #101

**Comment by jasonswearingen** [comment]
could you also please update the npm version to include this?

**Comment by jordanbtucker** [comment]
@jasonswearingen, yes. Please join in on the discussion in #113. I'll see about bumping the number ASAP. Thanks.
