### ISSUE TITLE
Wording on “strict subset of JavaScript”

### ISSUE THREAD

**Issue by vfaronov** [aseemk/json5#90]
[json5.org](http://json5.org/) says:

> JSON5 remains a strict subset of JavaScript

[JSON is not a strict subset of JavaScript](http://timelessrepo.com/json-isnt-a-javascript-subset), so either JSON5 isn’t one, too, or it doesn’t “remain” one.

**Comment by jordanbtucker** [comment]
There's discussion of this in #70
